### ISSUE TITLE
index.php里的代码改了之后未输出json配置

### ISSUE THREAD

**Issue by V1rtu0l** [thinkphp5-inaction/config-demo#1]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/45991825/160095295-f0fbb703-e23c-4770-b88f-e2fdc600bf06.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/45991825/160095349-d44aecf2-6684-479c-8258-af3c328a5f07.png">
希望大佬解惑

**Comment by V1rtu0l** [comment]
代码写错了，刚看见

**Comment by V1rtu0l** [comment]
我代码写错了....但是改好了之后页面无输出json

**Comment by xialeistudio** [comment]
代码贴出来
